package m119javalib;

public enum spec{NAME, TYPE, MODIFIER, RETURN, ARGUMENT, ARGUMENT_TYPE, ARGUMENT_NAME, CONTENT, PACKAGE, IMPORT, EXTENDS, IMPLEMENTS, METHODS, METHODS_NAME, METHODS_TYPE, METHODS_RETURN, METHODS_MODIFIER, METHODS_ARGUMENT, METHODS_CONTENT, PUBLIC, PRIVATE, PROTECTED, STATIC, FINAL, SYNCHRONIZED, VOLATILE, TRANSIENT, NATIVE, INTERFACE, ABSTRACT, STRICT }